from fastapi import APIRouter, UploadFile, File, BackgroundTasks, HTTPException
from fastapi.responses import FileResponse
from services.file_service import validate_and_save_upload, get_output_folder, cleanup_upload
from services.audio_service import process_audio_pipeline
from utils.scale import detect_key
import os

router = APIRouter()

@router.post("/upload")
async def upload_file(background_tasks: BackgroundTasks, file: UploadFile = File(...)):
    """
    Uploads an audio file, stores it safely, and queues it for background ML processing.
    """
    file_id, file_path = validate_and_save_upload(file)
    
    # Delegating to BackgroundTasks prevents blocking the current Request context
    background_tasks.add_task(process_audio_pipeline, file_path, file_id)
    
    return {
        "message": "File uploaded successfully. Processing initiated.",
        "file_id": file_id,
        "status_url": f"/status/{file_id}"
    }

@router.post("/scale")
async def detect_scale_direct(file: UploadFile = File(...)):
    """
    Fast-track API: skips the heavy ML source separation. 
    Runs the algorithm directly on the uploaded input buffer for immediate response!
    """
    file_id, file_path = validate_and_save_upload(file)
    
    try:
        key_info = detect_key(file_path)
    finally:
        # Prevent disk explosion by self-cleaning
        cleanup_upload(file_path)
        
    return key_info


@router.get("/status/{file_id}")
def check_status(file_id: str):
    """
    Checks if processing for a file_id is fully completed.
    Returns 200 with available assets context.
    """
    song_folder = get_output_folder(file_id)
    
    if not song_folder.exists():
        # Demucs takes a few seconds to initialize its model before the output folder is created.
        # So if it doesn't exist yet, we assume it's still booting up processing!
        return {"status": "processing", "file_id": file_id}
        
    key_path = song_folder / "key.json"
    
    # Simple heuristic: key.json is the final step
    if key_path.exists():
        files_available = [f.name for f in song_folder.glob("*.wav")] + ["key.json"]
        return {
            "status": "completed",
            "file_id": file_id,
            "files_available": files_available
        }
        
    return {"status": "processing", "file_id": file_id}


@router.get("/download/{file_id}/{file_type}")
def download_file(file_id: str, file_type: str):
    """
    Downloads an artifact (e.g. vocals.wav, karaoke.wav, notes.json) 
    that was fully generated by the pipeline.
    """
    safe_file_type = os.path.basename(file_type)
    song_folder = get_output_folder(file_id)
    file_path = song_folder / safe_file_type
    
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="File not found or still processing")
        
    media_type = "application/json" if safe_file_type.endswith(".json") else "audio/wav"
    return FileResponse(
        path=file_path, 
        filename=f"{file_id}_{safe_file_type}", 
        media_type=media_type
    )
